### ISSUE TITLE
Account Switcher

### ISSUE THREAD

**Issue by Slymeball** [vendetta-mod/ideas#229] opened 2023-12-25 17:46 UTC
### Discord username

@slyme.the.slime

### Plugin description

A plugin that allows users to swap to a different user account without having to log out/in every time.

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment] 2023-12-25 17:48
Duplicate of #34, #102, #108

**Closed as not planned by Cynosphere** 2023-12-25 17:48 UTC
Labels: Duplicate, Plugin
