### ISSUE TITLE
Reaction notifer

### ISSUE THREAD

**Issue by Adara1120** [vendetta-mod/ideas#122] opened 2023-08-26 23:26 UTC
### Discord username

adarabluelanterncorpsentity

### Plugin description

Sends you in-app notifications when someone reacts to your message

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment] 2023-08-27 00:30
Duplicate of #86

**Closed as not planned by Cynosphere** 2023-08-27 00:30 UTC
Labels: Duplicate, Plugin

**Comment by Adara1120** [comment] 2023-08-27 00:31
> Duplicate of #86 

💀
