### ISSUE TITLE
Better Folders

### ISSUE THREAD

**Issue by TakiShiwa** [vendetta-mod/ideas#93] opened 2023-08-04 12:51 UTC
### Plugin description

A plugin which will work like the better folder plugin (in venchord). 

### Elaborate

A plugin which will replace the traditional cluttered multiple server icons with just a simple folder icon.
Like this 
![image](https://github.com/vendetta-mod/ideas/assets/137756384/0f5ef5e0-0f5f-4fe9-a5bb-4dcfb1aa0143)

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment] 2023-08-04 15:45
Duplicate of #66

**Closed as not planned** 2023-08-04 16:52 UTC
Labels: Duplicate, Plugin
