### ISSUE TITLE
No sounds

### ISSUE THREAD

**Issue by dyrakfifa** [vendetta-mod/ideas#206] opened 2023-11-21 21:29 UTC
### Discord username

qwersys_

### Plugin description

please make a plugin that turns off sounds: turning on the stream, turning on/off the microphone, joining a voice channel, etc.  Or like in bluecord, the same thing, but when the phone is on silent / vibration

### Elaborate

sounds while in the apk along the res/raw path

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment] 2023-11-21 21:31
Duplicate of #173

**Closed as not planned by Cynosphere** 2023-11-21 21:31 UTC
Labels: Duplicate, Plugin
