### ISSUE TITLE
Plugin to set custom playing/watching status

### ISSUE THREAD

**Issue by itstheAmir** [vendetta-mod/ideas#176] opened 2023-10-22 17:34 UTC
### Plugin description

A plugin, like the chrome extension which allows you to set custom playing/watching statuses. For example, a status that says "Playing Hello" or "Watching YouTube".

### Elaborate

Since there is already a chrome extension for that, I don't think it's impossible to make such plugin. I guess you can trick the server and it's not a server side feature, it's all about the client. So the plugin is possible to make. 

### ​

- [X] I have verified that this request is indeed original

**Comment by nexpid** [comment] 2023-10-22 17:35
https://vendetta.nexpid.xyz/customrpc exists, altough it's unfinished and unproxied (also duplicate of #43 )

**Closed as not planned** 2023-10-22 17:36 UTC
Labels: Duplicate, Plugin
