### ISSUE TITLE
Show username instead of their id

### ISSUE THREAD

**Issue by Dawimpy** [vendetta-mod/ideas#80] opened 2023-07-23 10:44 UTC
### Discord username

dawimpy 

### Plugin description

Fix mentions for unknown users showing up

https://vencord.dev/plugins/ValidUser

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment] 2023-08-27 00:31
Duplicate of #35

**Closed as not planned by Cynosphere** 2023-08-27 00:31 UTC
Labels: Duplicate, Plugin
