### ISSUE TITLE
Disable noise suppression for Voice Messages

### ISSUE THREAD

**Issue by XAlboX** [vendetta-mod/ideas#226] opened 2023-12-18 16:55 UTC
### Discord username

@alboook

### Plugin description

Read Title :o

### Elaborate

There is no way to do that. Even if u disable noise suppression in Voice & Video it remains enabled for voice messages and the sound quality is poor...

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment] 2023-12-18 18:20
Duplicate of #157

**Closed as not planned by Cynosphere** 2023-12-18 18:20 UTC
Labels: Duplicate, Plugin
