### ISSUE TITLE
Scheduled messaging

### ISSUE THREAD

**Issue by Adara1120** [vendetta-mod/ideas#117] opened 2023-08-26 22:07 UTC
### Discord username

adarabluelanterncorpsentity

### Plugin description

You could set up a time to send someone a message in DM or if applicable servers too

### Elaborate

I think this would be a cool feature if you need to send someone a message at a certain time

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment] 2023-08-27 00:05
Duplicate of #96

**Closed as not planned** 2023-08-27 00:21 UTC
Labels: Duplicate, Plugin
