### ISSUE TITLE
AutoRelpy Plugin

### ISSUE THREAD

**Issue by MRVIP219** [vendetta-mod/ideas#170] opened 2023-10-16 22:38 UTC
### Discord username

@t_ps

### Plugin description

When Someone send to me hello this plugin reply to him allow and I can change the reply 
and make new reply from plugin settings

### ​

- [X] I have verified that this request is indeed original

**Comment by MRVIP219** [comment] 2023-10-16 22:39
> ### Discord username
> @t_ps
> 
> ### Plugin description
> When Someone send to me hello this plugin reply to him,  and I can change the reply and make new reply from plugin settings
> 
> ### Elaborate
> _No response_
> 
> ### ​
> * [x]  I have verified that this request is indeed original

**Comment by Cynosphere** [comment] 2023-10-16 22:42
Duplicate of #118 and #150

**Closed as not planned by Cynosphere** 2023-10-16 22:42 UTC
Labels: Duplicate, Invalid, Plugin
