### ISSUE TITLE
Auto-Reply

### ISSUE THREAD

**Issue by ThumbCraftian** [vendetta-mod/ideas#150] opened 2023-10-01 16:25 UTC
### Discord username

@beserker25

### Plugin description

Automatically responds to certain messages in servers you're in.

### Elaborate

So, for example; as with the text replacement plugin, you could make certain rules that dictate what gets replied to with what. Now, if that option is not okay, then i have another idea; Have it so You automatically reply "Hai" to anyone in any server (in channels you can access) who says "Hello".

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment] 2023-10-01 16:26
Duplicate of #118 
> Falls into "selfbotty" category. Automated message sending is not an ideal thing to have in a lot of our opinions.

**Closed as not planned by Cynosphere** 2023-10-01 16:26 UTC
Labels: Duplicate, Invalid, Plugin
