### ISSUE TITLE
ClearURLs from Vencord to Vendetta

### ISSUE THREAD

**Issue by XAlboX** [vendetta-mod/ideas#133] opened 2023-09-09 16:25 UTC
### Discord username

@alboook

### Plugin description

It will be more effective than TextReplace, we can keep that one for something else, just like Vencord does...

### Elaborate

It would be nice if the plugin could remove the tracking parameters from the urls of YT, Instagram etc.

### ​

- [X] I have verified that this request is indeed original

**Comment by nexpid** [comment] 2023-09-09 16:27
grabbing

**Comment by Cynosphere** [comment] 2023-09-09 17:00
Duplicate of #45

**Closed as not planned by Cynosphere** 2023-09-09 17:00 UTC
Labels: Duplicate, Plugin
