### ISSUE TITLE
Text React

### ISSUE THREAD

**Issue by mudrhiod** [vendetta-mod/ideas#130] opened 2023-09-07 17:56 UTC
### Discord username

Moodle.v2

### Plugin description

A plugin that lets users text react on a message easily (like the one on aliucord where you hold a message, click text react, input text and it'll add those reactions)

### ​

- [ ] I have verified that this request is indeed original

**Comment by Cynosphere** [comment] 2023-09-07 17:57
Duplicate of #25

**Closed as not planned by Cynosphere** 2023-09-07 17:57 UTC
Labels: Duplicate, Plugin

**Comment by mudrhiod** [comment] 2023-09-07 18:06
Oops
