### ISSUE TITLE
password

### ISSUE THREAD

**Issue by Celestemysterios** [vendetta-mod/ideas#186] opened 2023-10-27 19:07 UTC
### Discord username

celestemyst

### Plugin description

basically it makes it to where you must enter a pin/password you set to enter into discord

### Elaborate

you might be wondering "why"
2 reasons i can think of
1. lets say someone stole someone elses phone and went and somehow got on the phone, this plugin could be extra security
2. ~~me dont want my parents going on it and seeing stuff~~

### ​

- [X] I have verified that this request is indeed original

**Comment by Cynosphere** [comment] 2023-10-27 19:47
Duplicate of #132

**Closed as not planned by Cynosphere** 2023-10-27 19:47 UTC
Labels: Duplicate, Plugin
