### ISSUE TITLE
An account switcher plugin for mobile

### ISSUE THREAD

**Issue by MrSqueakss** [vendetta-mod/ideas#108] opened 2023-08-21 00:19 UTC
### Discord username

@boayer

### Plugin description

Make a plugin that you can press a button to switch between accounts so I don't have to put in passwords every time.

### ​

- [X] I have verified that this request is indeed original

**Comment by nexpid** [comment] 2023-08-21 00:42
![maxresdefault](https://github.com/vendetta-mod/ideas/assets/60316309/9a24e413-e09e-4619-9d4c-2f454f32765a)

**Comment by TakiShiwa** [comment] 2023-08-21 08:12
> ### Discord username
> 
> @Boayer
> ### Plugin description
> 
> Make a plugin that you can press a button to switch between accounts so I don't have to put in passwords every time.
> ### Elaborate
> 
> _No response_
> ### ​
> 
>     * [x]  I have verified that this request is indeed original

Boy use experiments, it's already in the discord

**Comment by Cynosphere** [comment] 2023-08-27 00:11
Duplicate of #102

**Closed as not planned** 2023-08-27 00:20 UTC
Labels: Duplicate, Plugin
